# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Routes can be defined explicitly or using PHP attributes.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

api_login:
    path: /api/login
    controller: App\Controller\ApiController::login
    methods: [POST]

api_registro:
    path: /api/registro
    controller: App\Controller\ApiController::registro
    methods: [POST]

api_productos_get:
    path: /api/productos
    controller: App\Controller\ApiController::productos
    methods: [GET]

api_productos_post:
    path: /api/productos
    controller: App\Controller\ApiController::crearProducto
    methods: [POST]

api_productos_put:
    path: /api/productos/{id}
    controller: App\Controller\ApiController::editarProducto
    methods: [PUT]

api_productos_delete:
    path: /api/productos/{id}
    controller: App\Controller\ApiController::eliminarProducto
    methods: [DELETE]

controllers:
    resource: '../src/Controller/'
    type: attribute
